using System;
using AirportSim.App.Render.Art2D;
using UnityEngine;

namespace AirportSim.App.Render.Unity
{
    /// <summary>
    /// The Unity render backend (15 §15.10). Lives on the scene's main camera object. The bootstrap
    /// (16 §16.7) calls <see cref="ReadCameraView"/> and <see cref="Draw"/> once per engine frame; this
    /// component runs no frame order, calls no sim member and issues no command.
    /// </summary>
    [RequireComponent(typeof(Camera))]
    public sealed class RenderBackend : MonoBehaviour
    {
        static readonly int RoleCount = Enum.GetValues(typeof(ColourRole)).Length;
        const int SceneLayer = 31;
        const int MsaaSamples = 4;
        const int InitialQuads = 4096;

        /// <summary>Colour per <see cref="ColourRole"/>; "maps ColourRole to colour through a palette asset".</summary>
        public RenderPalette Palette;

        /// <summary>Camera at scene start.</summary>
        public float StartCentreX;
        public float StartCentreY;
        public float StartViewHeight = 200f;

        /// <summary>Zoom limits and speed. They keep <c>ViewHeight</c> positive.</summary>
        public float MinViewHeight = 10f;
        public float MaxViewHeight = 5000f;
        public float ZoomPerNotch = 1.1f;

        Camera sceneCamera;     // renders the mesh into target
        Mesh mesh;              // the one mesh: every quad of Fill, in order
        Material material;      // the one material (Sprites/Default), with the one atlas texture
        RenderTexture target;
        ISpriteTessellator tessellator;
        Rgba[] roleColours;
        bool linear;
        Vector3[] vertices;
        Vector2[] uvs;
        Color32[] colours;
        int[] triangles;
        bool ready;

        WorldPoint centre;
        float viewHeight;
        Vector3 lastMouse;

        // Last applied graphics values (15 §15.10: apply only when they differ).
        int appliedFrameRateCap = -1;
        int appliedScalePercent = -1;
        bool appliedAntiAliasing;
        int appliedScreenWidth;
        int appliedScreenHeight;

        void Awake()
        {
            Shader shader = Shader.Find("Sprites/Default");   // vertex colour, no depth write: triangle order is draw order
            if (Palette == null || Palette.Roles.Length != RoleCount || shader == null)
            {
                Debug.LogError("RenderBackend: needs a palette with one colour per ColourRole, and the Sprites/Default shader.");
                return;
            }

            // The palette asset becomes Rgba once (15 §15.10).
            roleColours = new Rgba[RoleCount];
            for (int i = 0; i < RoleCount; i++)
            {
                Color32 c = Palette.Roles[i];
                roleColours[i] = new Rgba(c.r, c.g, c.b, c.a);
            }

            tessellator = Art2DFactory.CreateTessellator();
            linear = QualitySettings.activeColorSpace == ColorSpace.Linear;

            // The presenter is this object's camera: it draws nothing itself and copies target to the screen.
            Camera presenter = GetComponent<Camera>();
            presenter.cullingMask = 0;
            presenter.clearFlags = CameraClearFlags.SolidColor;
            presenter.backgroundColor = Color.black;
            presenter.depth = 0;

            var go = new GameObject("RenderBackend scene camera", typeof(Camera));
            go.transform.SetParent(transform, false);
            sceneCamera = go.GetComponent<Camera>();
            sceneCamera.orthographic = true;
            sceneCamera.cullingMask = 1 << SceneLayer;
            sceneCamera.clearFlags = CameraClearFlags.SolidColor;
            sceneCamera.backgroundColor = Palette.Background;
            sceneCamera.depth = -1;

            material = new Material(shader);
            material.mainTexture = UploadAtlas();
            mesh = new Mesh();
            mesh.MarkDynamic();
            Grow(InitialQuads);

            centre = new WorldPoint(StartCentreX, StartCentreY);
            viewHeight = Mathf.Clamp(StartViewHeight, MinViewHeight, MaxViewHeight);
            ApplyTarget(100, false);
            ready = true;
        }

        // The atlas goes up once, as given: every mip level set from Mips[m], none generated by the engine, sRGB,
        // trilinear, clamped, not readable afterwards. No reference to the SpriteAtlas outlives this method.
        static Texture2D UploadAtlas()
        {
            SpriteAtlas atlas = Art2DFactory.BuildAtlas();
            var texture = new Texture2D(atlas.Size, atlas.Size, TextureFormat.RGBA32, Art2DConstants.ATLAS_MIP_COUNT, false);
            for (int m = 0; m < Art2DConstants.ATLAS_MIP_COUNT; m++)
            {
                texture.SetPixelData(atlas.Mips[m], m);
            }

            texture.filterMode = FilterMode.Trilinear;
            texture.wrapMode = TextureWrapMode.Clamp;
            texture.Apply(false, true);
            return texture;
        }

        void OnDestroy()
        {
            if (target != null)
            {
                target.Release();
                Destroy(target);
            }

            if (mesh != null)
            {
                Destroy(mesh);
            }

            if (material != null)
            {
                Destroy(material.mainTexture);
                Destroy(material);
            }

            if (sceneCamera != null)
            {
                Destroy(sceneCamera.gameObject);
            }
        }

        /// <summary>
        /// Turns this frame's pan (right or middle mouse drag) and zoom (scroll wheel) into the
        /// <see cref="CameraView"/>. <c>ViewHeight</c> stays within positive limits and <c>Aspect</c>
        /// is the full-screen width over height.
        /// </summary>
        public CameraView ReadCameraView()
        {
            float screenHeight = Mathf.Max(1, Screen.height);
            Vector3 mouse = Input.mousePosition;
            bool held = Input.GetMouseButton(1) || Input.GetMouseButton(2);
            bool started = Input.GetMouseButtonDown(1) || Input.GetMouseButtonDown(2);
            if (held && !started)
            {
                float worldPerPixel = viewHeight / screenHeight;
                centre = new WorldPoint(
                    centre.X - (mouse.x - lastMouse.x) * worldPerPixel,
                    centre.Y - (mouse.y - lastMouse.y) * worldPerPixel);
            }

            lastMouse = mouse;

            float scroll = Input.mouseScrollDelta.y;
            if (scroll != 0f)
            {
                viewHeight = Mathf.Clamp(viewHeight * Mathf.Pow(ZoomPerNotch, -scroll), Mathf.Max(MinViewHeight, 0.001f), MaxViewHeight);
            }

            return new CameraView(centre, viewHeight, Mathf.Max(1, Screen.width) / screenHeight);
        }

        /// <summary>Applies the frame's graphics knobs if they changed, then draws its primitives in list order.</summary>
        public void Draw(in RenderFrame frame)
        {
            if (!ready)
            {
                return;
            }

            GraphicsSettings g = frame.Graphics;
            if (g.FrameRateCap != appliedFrameRateCap)
            {
                QualitySettings.vSyncCount = 0;   // targetFrameRate is ignored while vsync is on
                Application.targetFrameRate = g.FrameRateCap == 0 ? -1 : g.FrameRateCap;
                appliedFrameRateCap = g.FrameRateCap;
            }

            ApplyTarget(g.ResolutionScalePercent, g.AntiAliasing);

            CameraView view = frame.Camera;
            sceneCamera.orthographicSize = view.ViewHeight * 0.5f;
            sceneCamera.aspect = view.Aspect;
            sceneCamera.transform.position = new Vector3(view.Centre.X, view.Centre.Y, -10f);

            FillMesh(tessellator.Fill(frame, roleColours, linear));
            Graphics.DrawMesh(mesh, Matrix4x4.identity, material, SceneLayer, sceneCamera);   // one draw call for every layer and role
        }

        // Resolution scale and anti-aliasing: the scene renders into a texture of scale% of the screen
        // (MSAA when on) that is stretched to the full screen. Camera, FrameInput and clicks are unaffected.
        void ApplyTarget(int scalePercent, bool antiAliasing)
        {
            if (target != null
                && scalePercent == appliedScalePercent
                && antiAliasing == appliedAntiAliasing
                && Screen.width == appliedScreenWidth
                && Screen.height == appliedScreenHeight)
            {
                return;
            }

            sceneCamera.targetTexture = null;
            if (target != null)
            {
                target.Release();
                Destroy(target);
            }

            target = new RenderTexture(Mathf.Max(1, Screen.width * scalePercent / 100), Mathf.Max(1, Screen.height * scalePercent / 100), 0)
            {
                antiAliasing = antiAliasing ? MsaaSamples : 1,
                filterMode = FilterMode.Bilinear,
            };
            sceneCamera.targetTexture = target;
            appliedScalePercent = scalePercent;
            appliedAntiAliasing = antiAliasing;
            appliedScreenWidth = Screen.width;
            appliedScreenHeight = Screen.height;
        }

        void OnRenderImage(RenderTexture source, RenderTexture destination)
        {
            if (target != null)
            {
                Graphics.Blit(target, destination);
            }
        }

        // Copies the tessellator's quads as given: four vertices each, in its corner order. No geometry, UV or colour of its own.
        void FillMesh(int count)
        {
            if (count * 4 > vertices.Length)
            {
                Grow(count);
            }

            float[] corners = tessellator.Corners;
            float[] quadUvs = tessellator.Uvs;
            byte[] quadColours = tessellator.Colours;
            int vertexCount = count * 4;
            for (int i = 0; i < vertexCount; i++)
            {
                int c = i * 2;
                int b = i * 4;
                vertices[i] = new Vector3(corners[c], corners[c + 1], 0f);
                uvs[i] = new Vector2(quadUvs[c], quadUvs[c + 1]);
                colours[i] = new Color32(quadColours[b], quadColours[b + 1], quadColours[b + 2], quadColours[b + 3]);
            }

            mesh.Clear(false);
            mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            mesh.SetVertices(vertices, 0, vertexCount);
            mesh.SetUVs(0, uvs, 0, vertexCount);
            mesh.SetColors(colours, 0, vertexCount);
            mesh.SetTriangles(triangles, 0, count * 6, 0, false);
            mesh.bounds = new Bounds(Vector3.zero, new Vector3(1e6f, 1e6f, 1e6f));
        }

        // Managed scratch arrays only; they grow when a frame holds more quads than ever before.
        void Grow(int quadCount)
        {
            int capacity = InitialQuads;
            while (capacity < quadCount)
            {
                capacity *= 2;
            }

            vertices = new Vector3[capacity * 4];
            uvs = new Vector2[capacity * 4];
            colours = new Color32[capacity * 4];
            triangles = new int[capacity * 6];
            for (int i = 0; i < capacity; i++)
            {
                int v = i * 4;
                int t = i * 6;
                triangles[t] = v;
                triangles[t + 1] = v + 1;
                triangles[t + 2] = v + 2;
                triangles[t + 3] = v;
                triangles[t + 4] = v + 2;
                triangles[t + 5] = v + 3;
            }
        }
    }
}
